### PR TITLE
added exceptional handling

### PR DESCRIPTION
**Pull request by rashedmyt**
@arthurk I have added some exceptional handling so that any application using this RPC won't quit abruptly, but the developer of the application has to write some if/else statements to check for empty string on receiving response from the request.

### CODE REVIEW

**Comment by arthurk** [comment]
I think it's better that we raise exceptions and let the developer handle them instead of returning an empty string. For example if I run the app and it raises `JSONDecodeError` i know that the decoding of the JSON failed but with an empty string it could be anything that failed.

My suggestion would be to document how to handle errors, which is basically what you did in the code (try/except)

**Comment by Sajo811** [comment]
Maybe return a string: “JSONDecodeError: Make sure you did daz right dud”,  instead of returning an empty string or just letting the thing crash

**Comment by Sajo811** [comment]
And sometimes I get a JSONDecodeError when I try to connect to public.turtlenode.io: you could add that in the string

**Comment by rashedmyt** [comment]
Oops.. I didn't know that raise keyword throws the exception so that the calling function should handle. I will fix the PR to support it

This is what happens when we don't get familiarity with all parts of a language

**Comment by rashedmyt** [comment]
@arthurk I think this PR isn't required.. its just extra burden of code.. I am closing this.

@Sajo811 I will do the error handling in your bot..

**Comment by Sajo811** [comment]
uh.. o-ok

**Pull request closed without merging**
