### PR TITLE
Turtlecoind rpc patch

### PR DESCRIPTION
**Pull request by rashedmyt**
Complete JSON RPC methods have been implemented..

@arthurk can you please review and merge the changes

@RocksteadyTC Can you change the name of repo to turtlecoin-rpc-python since it contains both walletd and TurtleCoind JSON RPC methods

### CODE REVIEW

**Comment by rashedmyt** [comment]
thanks.. @RocksteadyTC

**Comment by arthurk** [comment]
@rashedmyt  Let me know when this PR is ready to be merged

**Comment by rashedmyt** [comment]
It's complete unless I need to add the HTTP RPC methods

**Comment by arthurk** [comment]
Up to you, I can merge this PR and can you make another one? I think it would be faster to review 2 small PRs instead of a large one

**Comment by rashedmyt** [comment]
Sure.. I will make another one after testing the http rpc methods.. this can be merged

**Pull request merged**
